version: "3.6"

services:
  so1:
    image: ${SPLUNK_IMAGE:-splunk/splunk:latest}
    container_name: so1
    environment:
      - SPLUNK_START_ARGS=--accept-license
      - SPLUNK_PASSWORD==YourSecurePassword123!
    ports:
      - 8000:8000
      - 8089:8089
      - 9997:9997
      - 1514:1514/udp
    volumes:
      - ${APP_DATA_DIR}/etc:/opt/splunk/etc
      - ${APP_DATA_DIR}/var:/opt/splunk/var
    restart: unless-stopped
